name: Template - Scrypto Package CI - Linut and Test

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      scrypto_version:
        required: true
        type: string
      create_release:
        required: false
        type: boolean
    
jobs:
  scrypto-lint-and-test:
    name: Check and Lint
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/weftfinance/scrypto-builder:${{inputs.scrypto_version}}
      env:
        DOCKER_DEFAULT_PLATFORM: linux/amd64/v4
      volumes:
        - ${{github.workspace}}:/src

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Check format and lint
        run: |
          cd "${{ inputs.package }}"
          cargo fmt -- --check
          cargo clippy -- -D warnings
          cargo audit
          cargo test --quiet
          
      # - name: Test Blueprints
      #   run: |
      #     cd "${{ inputs.package }}"
      #     scrypto test
