name: Template - Scrypto Package CI 

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      scrypto_version:
        required: true
        type: string
      create_release:
        required: false
        type: boolean
    
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6

  scrypto-test-and-build:
    name: Check and Lint
    needs: spellcheck
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/weftfinance/scrypto-builder:${{inputs.scrypto_version}}
      env:
        DOCKER_DEFAULT_PLATFORM: linux/amd64/v4
      volumes:
        - ${{github.workspace}}:/src

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Check format and lint
        run: |
          cd "${{ inputs.package }}"
          cargo fmt -- --check
          cargo clippy -- -D warnings
          cargo audit --ignore RUSTSEC-2022-0093
          
      - name: Test Blueprints
        run: |
          cd "${{ inputs.package }}"
          scrypto test